# -*- coding: utf-8 -*-
"""simple_linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GD4du1U4WCFNrZorydgdW-41lGeEqpvX

# Simple Linear Regression

## Importing the libraries
"""

import numpy as np;
import pandas as pd;
import matplotlib.pyplot as plt;

"""## Importing the dataset"""

df = pd.read_csv("/content/Salary_Data.csv")
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

print(X)

print(y)

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 1)

print(X_train)

print(X_test)

print(y_train)

print(y_test)

"""## Training the Simple Linear Regression model on the Training set"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

"""## Predicting the Test set results"""

y_pred = regressor.predict(X_test)

"""## Visualising the Training set results"""

plt.scatter(X_train,y_train,color="red")
plt.plot(X_train,regressor.predict(X_train),color = "blue")
plt.title("Salary vs Experince(Training Set)")
plt.xlabel("Years of Experince")
plt.ylabel("Salary")
plt.show()

"""## Visualising the Test set results"""

plt.scatter(X_test,y_test,color="red")
plt.plot(X_train,regressor.predict(X_train),color="blue")
plt.title("Salary vs Experince(Test Set)")
plt.xlabel("Years of Experince")
plt.ylabel("Salary")
plt.show()